// Protobuf definition for RBAC system

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: proto/rbac.proto

package rbacservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Effect int32

const (
	Effect_ALLOW Effect = 0
	Effect_DENY  Effect = 1
)

// Enum value maps for Effect.
var (
	Effect_name = map[int32]string{
		0: "ALLOW",
		1: "DENY",
	}
	Effect_value = map[string]int32{
		"ALLOW": 0,
		"DENY":  1,
	}
)

func (x Effect) Enum() *Effect {
	p := new(Effect)
	*p = x
	return p
}

func (x Effect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Effect) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rbac_proto_enumTypes[0].Descriptor()
}

func (Effect) Type() protoreflect.EnumType {
	return &file_proto_rbac_proto_enumTypes[0]
}

func (x Effect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Effect.Descriptor instead.
func (Effect) EnumDescriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{0}
}

type PolicyId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // UUID as a string
}

func (x *PolicyId) Reset() {
	*x = PolicyId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rbac_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyId) ProtoMessage() {}

func (x *PolicyId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyId.ProtoReflect.Descriptor instead.
func (*PolicyId) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PolicyStatement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatementId string   `protobuf:"bytes,1,opt,name=statement_id,json=statementId,proto3" json:"statement_id,omitempty"`
	Resources   []string `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	Actions     []string `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	Effect      Effect   `protobuf:"varint,4,opt,name=effect,proto3,enum=edmondop.api.rbac.v1.Effect" json:"effect,omitempty"`
}

func (x *PolicyStatement) Reset() {
	*x = PolicyStatement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rbac_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyStatement) ProtoMessage() {}

func (x *PolicyStatement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyStatement.ProtoReflect.Descriptor instead.
func (*PolicyStatement) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyStatement) GetStatementId() string {
	if x != nil {
		return x.StatementId
	}
	return ""
}

func (x *PolicyStatement) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *PolicyStatement) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *PolicyStatement) GetEffect() Effect {
	if x != nil {
		return x.Effect
	}
	return Effect_ALLOW
}

type AddPolicyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Statements []*PolicyStatement `protobuf:"bytes,1,rep,name=statements,proto3" json:"statements,omitempty"`
	Roles      []string           `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *AddPolicyRequest) Reset() {
	*x = AddPolicyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rbac_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPolicyRequest) ProtoMessage() {}

func (x *AddPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPolicyRequest.ProtoReflect.Descriptor instead.
func (*AddPolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{2}
}

func (x *AddPolicyRequest) GetStatements() []*PolicyStatement {
	if x != nil {
		return x.Statements
	}
	return nil
}

func (x *AddPolicyRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type AssignPolicyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyId *PolicyId `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Roles    []string  `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *AssignPolicyRequest) Reset() {
	*x = AssignPolicyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rbac_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPolicyRequest) ProtoMessage() {}

func (x *AssignPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPolicyRequest.ProtoReflect.Descriptor instead.
func (*AssignPolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{3}
}

func (x *AssignPolicyRequest) GetPolicyId() *PolicyId {
	if x != nil {
		return x.PolicyId
	}
	return nil
}

func (x *AssignPolicyRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UnassignPolicyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyId *PolicyId `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Roles    []string  `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *UnassignPolicyRequest) Reset() {
	*x = UnassignPolicyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rbac_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnassignPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignPolicyRequest) ProtoMessage() {}

func (x *UnassignPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignPolicyRequest.ProtoReflect.Descriptor instead.
func (*UnassignPolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{4}
}

func (x *UnassignPolicyRequest) GetPolicyId() *PolicyId {
	if x != nil {
		return x.PolicyId
	}
	return nil
}

func (x *UnassignPolicyRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UpdatePolicyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyId *PolicyId `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Roles    []string  `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *UpdatePolicyRequest) Reset() {
	*x = UpdatePolicyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rbac_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolicyRequest) ProtoMessage() {}

func (x *UpdatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePolicyRequest) GetPolicyId() *PolicyId {
	if x != nil {
		return x.PolicyId
	}
	return nil
}

func (x *UpdatePolicyRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type AuthorizeActionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User     string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Resource string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Action   string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *AuthorizeActionRequest) Reset() {
	*x = AuthorizeActionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rbac_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizeActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeActionRequest) ProtoMessage() {}

func (x *AuthorizeActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeActionRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{6}
}

func (x *AuthorizeActionRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AuthorizeActionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuthorizeActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type PolicyIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyId *PolicyId `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Error    *string   `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"` // error message if any
}

func (x *PolicyIdResponse) Reset() {
	*x = PolicyIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rbac_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyIdResponse) ProtoMessage() {}

func (x *PolicyIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyIdResponse.ProtoReflect.Descriptor instead.
func (*PolicyIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{7}
}

func (x *PolicyIdResponse) GetPolicyId() *PolicyId {
	if x != nil {
		return x.PolicyId
	}
	return nil
}

func (x *PolicyIdResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *string `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // error message if any
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rbac_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{8}
}

func (x *ErrorResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type AuthorizeActionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorized bool    `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	Error      *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"` // error message if any
}

func (x *AuthorizeActionResponse) Reset() {
	*x = AuthorizeActionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rbac_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizeActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeActionResponse) ProtoMessage() {}

func (x *AuthorizeActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeActionResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{9}
}

func (x *AuthorizeActionResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

func (x *AuthorizeActionResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type AddUserToRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Role string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *AddUserToRoleRequest) Reset() {
	*x = AddUserToRoleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rbac_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserToRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserToRoleRequest) ProtoMessage() {}

func (x *AddUserToRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserToRoleRequest.ProtoReflect.Descriptor instead.
func (*AddUserToRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{10}
}

func (x *AddUserToRoleRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AddUserToRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AddUserToRoleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AddUserToRoleResponse) Reset() {
	*x = AddUserToRoleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rbac_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserToRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserToRoleResponse) ProtoMessage() {}

func (x *AddUserToRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserToRoleResponse.ProtoReflect.Descriptor instead.
func (*AddUserToRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{11}
}

func (x *AddUserToRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveUserFromRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Role string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *RemoveUserFromRoleRequest) Reset() {
	*x = RemoveUserFromRoleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rbac_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveUserFromRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromRoleRequest) ProtoMessage() {}

func (x *RemoveUserFromRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromRoleRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserFromRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveUserFromRoleRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RemoveUserFromRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetRolesForUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *GetRolesForUserRequest) Reset() {
	*x = GetRolesForUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rbac_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRolesForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolesForUserRequest) ProtoMessage() {}

func (x *GetRolesForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolesForUserRequest.ProtoReflect.Descriptor instead.
func (*GetRolesForUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{13}
}

func (x *GetRolesForUserRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type GetRolesForUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles []string `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *GetRolesForUserResponse) Reset() {
	*x = GetRolesForUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rbac_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRolesForUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolesForUserResponse) ProtoMessage() {}

func (x *GetRolesForUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolesForUserResponse.ProtoReflect.Descriptor instead.
func (*GetRolesForUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{14}
}

func (x *GetRolesForUserResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_proto_rbac_proto protoreflect.FileDescriptor

var file_proto_rbac_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x14, 0x65, 0x64, 0x6d, 0x6f, 0x6e, 0x64, 0x6f, 0x70, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x08, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xa2, 0x01, 0x0a, 0x0f, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x34, 0x0a, 0x06, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x65, 0x64, 0x6d, 0x6f, 0x6e, 0x64, 0x6f,
	0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x66,
	0x66, 0x65, 0x63, 0x74, 0x52, 0x06, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x22, 0x6f, 0x0a, 0x10,
	0x41, 0x64, 0x64, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x45, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x65, 0x64, 0x6d, 0x6f, 0x6e, 0x64, 0x6f, 0x70, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x68, 0x0a,
	0x13, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x09, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x65, 0x64, 0x6d, 0x6f, 0x6e, 0x64,
	0x6f, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x6a, 0x0a, 0x15, 0x55, 0x6e, 0x61, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x3b, 0x0a, 0x09, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x65, 0x64, 0x6d, 0x6f, 0x6e, 0x64, 0x6f, 0x70, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x49, 0x64, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f,
	0x6c, 0x65, 0x73, 0x22, 0x68, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x09, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x65, 0x64, 0x6d, 0x6f, 0x6e, 0x64, 0x6f, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x62, 0x61,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x52, 0x08, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x60, 0x0a,
	0x16, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x74, 0x0a, 0x10, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x09, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x65, 0x64, 0x6d, 0x6f, 0x6e, 0x64, 0x6f,
	0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x34, 0x0a, 0x0d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01,
	0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x5e, 0x0a, 0x17, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01,
	0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3e, 0x0a, 0x14, 0x41,
	0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x31, 0x0a, 0x15, 0x41,
	0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x43,
	0x0a, 0x19, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d,
	0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x22, 0x2c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x46,
	0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x22, 0x2f, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x46, 0x6f, 0x72,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c,
	0x65, 0x73, 0x2a, 0x1d, 0x0a, 0x06, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x12, 0x09, 0x0a, 0x05,
	0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x45, 0x4e, 0x59, 0x10,
	0x01, 0x32, 0x90, 0x06, 0x0a, 0x0b, 0x52, 0x62, 0x61, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x5b, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x26,
	0x2e, 0x65, 0x64, 0x6d, 0x6f, 0x6e, 0x64, 0x6f, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x62,
	0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x65, 0x64, 0x6d, 0x6f, 0x6e, 0x64, 0x6f,
	0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51,
	0x0a, 0x0c, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x29,
	0x2e, 0x65, 0x64, 0x6d, 0x6f, 0x6e, 0x64, 0x6f, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x62,
	0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x55, 0x0a, 0x0e, 0x55, 0x6e, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x12, 0x2b, 0x2e, 0x65, 0x64, 0x6d, 0x6f, 0x6e, 0x64, 0x6f, 0x70, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x61, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x51, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x29, 0x2e, 0x65, 0x64, 0x6d, 0x6f, 0x6e,
	0x64, 0x6f, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x6e, 0x0a, 0x0f, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c,
	0x2e, 0x65, 0x64, 0x6d, 0x6f, 0x6e, 0x64, 0x6f, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x62,
	0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x65,
	0x64, 0x6d, 0x6f, 0x6e, 0x64, 0x6f, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x62, 0x61, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x0d, 0x41,
	0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x2a, 0x2e, 0x65,
	0x64, 0x6d, 0x6f, 0x6e, 0x64, 0x6f, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x62, 0x61, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x52, 0x6f, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x65, 0x64, 0x6d, 0x6f, 0x6e,
	0x64, 0x6f, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x2f, 0x2e, 0x65, 0x64,
	0x6d, 0x6f, 0x6e, 0x64, 0x6f, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x46, 0x72, 0x6f,
	0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x6e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x73,
	0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x2c, 0x2e, 0x65, 0x64, 0x6d, 0x6f, 0x6e, 0x64,
	0x6f, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x65, 0x64, 0x6d, 0x6f, 0x6e, 0x64, 0x6f, 0x70,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x6f, 0x6c, 0x65, 0x73, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x65, 0x64, 0x6d, 0x6f, 0x6e, 0x64, 0x6f, 0x70, 0x2f, 0x72, 0x62, 0x61, 0x63,
	0x3b, 0x72, 0x62, 0x61, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_rbac_proto_rawDescOnce sync.Once
	file_proto_rbac_proto_rawDescData = file_proto_rbac_proto_rawDesc
)

func file_proto_rbac_proto_rawDescGZIP() []byte {
	file_proto_rbac_proto_rawDescOnce.Do(func() {
		file_proto_rbac_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_rbac_proto_rawDescData)
	})
	return file_proto_rbac_proto_rawDescData
}

var file_proto_rbac_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_rbac_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_rbac_proto_goTypes = []interface{}{
	(Effect)(0),                       // 0: edmondop.api.rbac.v1.Effect
	(*PolicyId)(nil),                  // 1: edmondop.api.rbac.v1.PolicyId
	(*PolicyStatement)(nil),           // 2: edmondop.api.rbac.v1.PolicyStatement
	(*AddPolicyRequest)(nil),          // 3: edmondop.api.rbac.v1.AddPolicyRequest
	(*AssignPolicyRequest)(nil),       // 4: edmondop.api.rbac.v1.AssignPolicyRequest
	(*UnassignPolicyRequest)(nil),     // 5: edmondop.api.rbac.v1.UnassignPolicyRequest
	(*UpdatePolicyRequest)(nil),       // 6: edmondop.api.rbac.v1.UpdatePolicyRequest
	(*AuthorizeActionRequest)(nil),    // 7: edmondop.api.rbac.v1.AuthorizeActionRequest
	(*PolicyIdResponse)(nil),          // 8: edmondop.api.rbac.v1.PolicyIdResponse
	(*ErrorResponse)(nil),             // 9: edmondop.api.rbac.v1.ErrorResponse
	(*AuthorizeActionResponse)(nil),   // 10: edmondop.api.rbac.v1.AuthorizeActionResponse
	(*AddUserToRoleRequest)(nil),      // 11: edmondop.api.rbac.v1.AddUserToRoleRequest
	(*AddUserToRoleResponse)(nil),     // 12: edmondop.api.rbac.v1.AddUserToRoleResponse
	(*RemoveUserFromRoleRequest)(nil), // 13: edmondop.api.rbac.v1.RemoveUserFromRoleRequest
	(*GetRolesForUserRequest)(nil),    // 14: edmondop.api.rbac.v1.GetRolesForUserRequest
	(*GetRolesForUserResponse)(nil),   // 15: edmondop.api.rbac.v1.GetRolesForUserResponse
	(*emptypb.Empty)(nil),             // 16: google.protobuf.Empty
}
var file_proto_rbac_proto_depIdxs = []int32{
	0,  // 0: edmondop.api.rbac.v1.PolicyStatement.effect:type_name -> edmondop.api.rbac.v1.Effect
	2,  // 1: edmondop.api.rbac.v1.AddPolicyRequest.statements:type_name -> edmondop.api.rbac.v1.PolicyStatement
	1,  // 2: edmondop.api.rbac.v1.AssignPolicyRequest.policy_id:type_name -> edmondop.api.rbac.v1.PolicyId
	1,  // 3: edmondop.api.rbac.v1.UnassignPolicyRequest.policy_id:type_name -> edmondop.api.rbac.v1.PolicyId
	1,  // 4: edmondop.api.rbac.v1.UpdatePolicyRequest.policy_id:type_name -> edmondop.api.rbac.v1.PolicyId
	1,  // 5: edmondop.api.rbac.v1.PolicyIdResponse.policy_id:type_name -> edmondop.api.rbac.v1.PolicyId
	3,  // 6: edmondop.api.rbac.v1.RbacService.AddPolicy:input_type -> edmondop.api.rbac.v1.AddPolicyRequest
	4,  // 7: edmondop.api.rbac.v1.RbacService.AssignPolicy:input_type -> edmondop.api.rbac.v1.AssignPolicyRequest
	5,  // 8: edmondop.api.rbac.v1.RbacService.UnassignPolicy:input_type -> edmondop.api.rbac.v1.UnassignPolicyRequest
	6,  // 9: edmondop.api.rbac.v1.RbacService.UpdatePolicy:input_type -> edmondop.api.rbac.v1.UpdatePolicyRequest
	7,  // 10: edmondop.api.rbac.v1.RbacService.AuthorizeAction:input_type -> edmondop.api.rbac.v1.AuthorizeActionRequest
	11, // 11: edmondop.api.rbac.v1.RbacService.AddUserToRole:input_type -> edmondop.api.rbac.v1.AddUserToRoleRequest
	13, // 12: edmondop.api.rbac.v1.RbacService.RemoveUserFromRole:input_type -> edmondop.api.rbac.v1.RemoveUserFromRoleRequest
	14, // 13: edmondop.api.rbac.v1.RbacService.GetRolesForUser:input_type -> edmondop.api.rbac.v1.GetRolesForUserRequest
	8,  // 14: edmondop.api.rbac.v1.RbacService.AddPolicy:output_type -> edmondop.api.rbac.v1.PolicyIdResponse
	16, // 15: edmondop.api.rbac.v1.RbacService.AssignPolicy:output_type -> google.protobuf.Empty
	16, // 16: edmondop.api.rbac.v1.RbacService.UnassignPolicy:output_type -> google.protobuf.Empty
	16, // 17: edmondop.api.rbac.v1.RbacService.UpdatePolicy:output_type -> google.protobuf.Empty
	10, // 18: edmondop.api.rbac.v1.RbacService.AuthorizeAction:output_type -> edmondop.api.rbac.v1.AuthorizeActionResponse
	12, // 19: edmondop.api.rbac.v1.RbacService.AddUserToRole:output_type -> edmondop.api.rbac.v1.AddUserToRoleResponse
	16, // 20: edmondop.api.rbac.v1.RbacService.RemoveUserFromRole:output_type -> google.protobuf.Empty
	15, // 21: edmondop.api.rbac.v1.RbacService.GetRolesForUser:output_type -> edmondop.api.rbac.v1.GetRolesForUserResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_rbac_proto_init() }
func file_proto_rbac_proto_init() {
	if File_proto_rbac_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_rbac_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rbac_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyStatement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rbac_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPolicyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rbac_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignPolicyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rbac_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnassignPolicyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rbac_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePolicyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rbac_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizeActionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rbac_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rbac_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rbac_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizeActionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rbac_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUserToRoleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rbac_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUserToRoleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rbac_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveUserFromRoleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rbac_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRolesForUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rbac_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRolesForUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_rbac_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_proto_rbac_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_proto_rbac_proto_msgTypes[9].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_rbac_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rbac_proto_goTypes,
		DependencyIndexes: file_proto_rbac_proto_depIdxs,
		EnumInfos:         file_proto_rbac_proto_enumTypes,
		MessageInfos:      file_proto_rbac_proto_msgTypes,
	}.Build()
	File_proto_rbac_proto = out.File
	file_proto_rbac_proto_rawDesc = nil
	file_proto_rbac_proto_goTypes = nil
	file_proto_rbac_proto_depIdxs = nil
}
